image: node:latest
stages:
  - build
  - test
fetch-dependencies:
  stage: build
  script:
    - npm install --legacy-peer-deps
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
run-jest:
  stage: test
  dependencies:
    - build
  image: node:latest
  script:
    - echo "Testing..."
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
