image: node:latest
stages:
  - build
  - test
build:
  stage: build
  script:
    - npm install --legacy-peer-deps
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
test:
  stage: test
  dependencies:
    - build
  image: node:latest
  script:
    - echo "Testing..."
    - npm run test:ci
